In [2]:
!pip install selenium
!pip install pandas

from selenium import webdriver
import pandas as pd
from time import sleep

Requirement already satisfied: selenium in c:\users\jeens\anaconda3\lib\site-packages

You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

Requirement already satisfied: pandas in c:\users\jeens\anaconda3\lib\site-packages
Requirement already satisfied: python-dateutil>=2 in c:\users\jeens\anaconda3\lib\site-packages (from pandas)
Requirement already satisfied: pytz>=2011k in c:\users\jeens\anaconda3\lib\site-packages (from pandas)
Requirement already satisfied: numpy>=1.9.0 in c:\users\jeens\anaconda3\lib\site-packages (from pandas)
Requirement already satisfied: six>=1.5 in c:\users\jeens\anaconda3\lib\site-packages (from python-dateutil>=2->pandas)

You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

In [8]:
driver = webdriver.Chrome('C:\Program Files (x86)\Google\Chrome\Application\chromedriver.exe')
url = 'http://topis.seoul.go.kr/refRoom/openRefRoom_1_3.do'
driver.get(url)

In [9]:
# 2017년 선택
year2017 = driver.find_element_by_xpath('//*[@id="selYear"]/option[7]')
year2017.click()

In [10]:
# 지역 선택
# 종로구 ~ 강동구 option[i] 돌리기 4 ~ 22
# 종로구 선택
selReg = driver.find_element_by_xpath('//*[@id="selRegCd"]/option[4]')
selReg.click()

In [11]:
# 월 선택
# 1 ~ 12 월까지 option[i] 돌리기 1 ~ 12
# for i in range(1,13) :
# selMon = driver.find_element_by_xpath('//*[@id="selMon"]/option['+str(i)+']')
selMon = driver.find_element_by_xpath('//*[@id="selMon"]/option[1]')
selMon.click()

In [28]:
selReg = driver.find_element_by_xpath('//*[@id="selRegCd"]/option[5]')
selReg.click()

In [29]:
# 오전, 낮, 오후, 전일, 전체, 시간대별 option[i] 돌리기 1 ~ 22
# 이 과정에서 오류가 한번이라도 나면 지역이 전체로 바뀜!!!
# 그래서 for문에 지역도 넣었음
for i in range(1,23) :
    # 종로구 선택
    selReg = driver.find_element_by_xpath('//*[@id="selRegCd"]/option[4]')
    selReg.click()
    # 시간 선택
    selTime = driver.find_element_by_xpath('//*[@id="selTimeGrp"]/option['+str(i)+']')
    selTime.click()
    sleep(5)
    # 검색
    search = driver.find_element_by_xpath('//*[@id="content"]/table/tbody/tr/td/table/tbody/tr/td[5]/button')
    search.click()
    sleep(5)
    # 엑셀 다운
    excel = driver.find_element_by_xpath('//*[@id="content"]/table/tbody/tr/td/table/tbody/tr/td[6]/button[1]')
    excel.click()
    sleep(5)
    
# for문이 5번 이상 돌면 404 error가 떠서 실패!

NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="selTimeGrp"]/option[7]"}
  (Session info: chrome=67.0.3396.99)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)

In [14]:
traffic = pd.read_excel('C:\\Users\jeens\OneDrive\Desktop\통행속도\차량통행속도.xls', encoding ='ANSI')
traffic = traffic.drop('날씨', axis = 1)
traffic = traffic.drop('최고온도(℃)', axis = 1)
traffic = traffic.drop('최저온도(℃)', axis = 1)
traffic.columns = ['일자', '0']
traffic.head()

         일자     0
0  20170101  32.2
1  20170102  25.6
2  20170103  26.2
3  20170104  26.5
4  20170105  26.5

In [15]:
for i in range(1,22) :
    traffic2 = pd.read_excel('C:\\Users\jeens\OneDrive\Desktop\통행속도\차량통행속도 ('+str(i)+').xls', encoding ='ANSI')
    traffic2 = traffic2.drop('날씨', axis = 1)
    traffic2 = traffic2.drop('최고온도(℃)', axis = 1)
    traffic2 = traffic2.drop('최저온도(℃)', axis = 1)
    traffic2.columns = ['일자', str(i)]
    traffic = pd.merge(traffic, traffic2, on='일자')

In [16]:
traffic.head()

,일자,0,1,2,3,4,5,6,7,8,...,12,13,14,15,16,17,18,19,20,21
0,20170101,32.2,26.9,25.5,28.1,29.3,33.9,33.0,32.5,31.9,...,27.6,26.2,25.9,25.4,25.2,25.2,25.9,26.9,27.3,28.3
1,20170102,25.6,26.2,23.1,25.5,28.1,33.5,30.4,26.6,24.6,...,26.5,25.9,25.1,24.6,24.3,23.7,22.5,23.0,25.8,27.0
2,20170103,26.2,25.2,21.5,24.5,27.2,33.8,31.0,27.6,24.8,...,25.3,25.0,24.1,23.4,23.0,22.3,20.8,21.1,24.4,26.2
3,20170104,26.5,25.2,21.4,24.6,27.2,33.6,31.2,27.9,25.1,...,25.3,25.0,24.1,23.4,23.1,22.2,20.5,20.9,24.6,26.3
4,20170105,26.5,25.0,21.2,24.5,27.1,33.8,31.3,28.0,25.0,...,25.1,24.8,23.8,23.2,22.8,21.9,20.5,21.4,24.9,26.3

In [17]:
traffic.columns = ['일자', '07-09', '12-14', '17-19', '06-22', '00-24', '06', '07', '08', '09', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22']

In [18]:
traffic.head()

,일자,07-09,12-14,17-19,06-22,00-24,06,07,08,09,...,13,14,15,16,17,18,19,20,21,22
0,20170101,32.2,26.9,25.5,28.1,29.3,33.9,33.0,32.5,31.9,...,27.6,26.2,25.9,25.4,25.2,25.2,25.9,26.9,27.3,28.3
1,20170102,25.6,26.2,23.1,25.5,28.1,33.5,30.4,26.6,24.6,...,26.5,25.9,25.1,24.6,24.3,23.7,22.5,23.0,25.8,27.0
2,20170103,26.2,25.2,21.5,24.5,27.2,33.8,31.0,27.6,24.8,...,25.3,25.0,24.1,23.4,23.0,22.3,20.8,21.1,24.4,26.2
3,20170104,26.5,25.2,21.4,24.6,27.2,33.6,31.2,27.9,25.1,...,25.3,25.0,24.1,23.4,23.1,22.2,20.5,20.9,24.6,26.3
4,20170105,26.5,25.0,21.2,24.5,27.1,33.8,31.3,28.0,25.0,...,25.1,24.8,23.8,23.2,22.8,21.9,20.5,21.4,24.9,26.3

In [ ]:
traffic.to_csv("C:\\Users\jeens\OneDrive\Desktop\통행속도\전체.csv", header = True, index = False)